services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql-server-container
    environment:
      SA_PASSWORD: periferiaItDb*
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    